version: '3'
volumes:
  blockdata_dir:
    external: true

services:
  rustcoin:
    build: ./rustcoin
    volumes: 
      - ./rustcoin:/opt/rustcoin
      - blockdata_dir:/root/.rustcoin/
    ports:
      - "8333:8333/udp"