[package]
name = "rustcoin"
version = "0.1.0"
authors = ["maxmcd <max.t.mcdonnell@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
time = "0.1.39"
secp256k1 = {version = "0.8", features = ["rand"]}
rand = "0.3"
rust-base58 = "0.0.4"
